relativeURLs = true
title = "Utkarsh Kumar"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Economic PhD Candidate, Columbia University"
    shortbio = "Columbia University"
    logo = "kumar_headshot.jpg"
