relativeURLs = true
title = "Utkarsh Kumar"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Economics Candidate"
    shortbio1 = "Columbia University"
    logo = "kumar_headshot1.jpg"
